### ISSUE TITLE
You can consider using jasync-sql which is a fork of mauricio mysql

### ISSUE THREAD

**Issue by oshai** [bj-tydic/async-mysql-connector#2]
Check if it fits your needs: https://github.com/jasync-sql/jasync-sql
It is a Java async database driver for MySQL and PostgreSQL

**Comment by shi-hailong** [comment]
做这个的主要目的是为了在使用MySQL官方驱动的前提下做异步处理。 如果基于MySQL通信协议来做，确实有更多选择。
